hello-world-configmap:
  replicaCount: 4
  app:
    content: |
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <meta http-equiv="refresh" content="0; url=https://www.nu.nl/">
        <title>Redirect</title>
      </head>
      <body>
        <p>Je wordt doorgestuurd naar <a href="https://www.nu.nl/">nu.nl</a></p>
      </body>
      </html>
